# -*- coding: utf-8 -*-
"""Static UI index data for the Python-built settings dialog."""

from __future__ import annotations

# Columns: N, UI, class, objectName, caption, tab, section, settingKey, default, notes
UI_INDEX = [('N001',
  'UI#001',
  'QLabel',
  'lblGeneralDescription',
  'General description',
  'General',
  'Description',
  '',
  '',
  'Explains simple general settings'),
 ('N002',
  'UI#002',
  'QCheckBox',
  'chkEnabled',
  'Enable Browse Enhancer',
  'General',
  'General',
  'enabled',
  'True',
  'Global plugin enable toggle'),
 ('N003',
  'UI#003',
  'QTabWidget',
  'tabSettings',
  'Settings tabs',
  'General',
  'Root',
  '',
  '',
  'Tabs grouped by button/path-box type'),
 ('N004',
  'UI#004',
  'QGroupBox',
  'grpApplyTo',
  'Apply to',
  'General',
  'Apply to',
  '',
  '',
  'General apply-to checkboxes'),
 ('N005',
  'UI#005',
  'QCheckBox',
  'chkApplySaveExport',
  'Apply to Save / Export buttons',
  'General',
  'Apply to',
  'apply/save_export',
  'True',
  'Recommended default'),
 ('N006',
  'UI#006',
  'QCheckBox',
  'chkApplySaveFile',
  'Apply to Save-file path boxes',
  'General',
  'Apply to',
  'apply/save_file',
  'False',
  'Opt-in save-file boxes'),
 ('N007',
  'UI#007',
  'QCheckBox',
  'chkApplyFolder',
  'Apply to Folder path boxes',
  'General',
  'Apply to',
  'apply/folder',
  'False',
  'Opt-in folder boxes'),
 ('N008',
  'UI#008',
  'QCheckBox',
  'chkApplyOpenFile',
  'Apply to Open-file path boxes',
  'General',
  'Apply to',
  'apply/open_file',
  'False',
  'Opt-in open-file boxes'),
 ('N009',
  'UI#009',
  'QCheckBox',
  'chkApplyLegacy',
  'Apply to Custom / Advanced Buttons',
  'General',
  'Apply to',
  'apply/legacy',
  'False',
  'Opt-in custom/advanced button mode; normal QgsFileWidget tabs unaffected'),
 ('N010',
  'UI#011',
  'QPushButton',
  'btnRestoreDefaults',
  'Restore defaults',
  'Dialog buttons',
  'Dialog',
  '',
  '',
  'Restores default settings; placed beside Save settings'),
 ('N011',
  'UI#012',
  'QLabel',
  'lblPresetMenuDescription',
  'Preset path menu description',
  'Preset path menu',
  'Description',
  '',
  '',
  'Explains preset path menu configuration'),
 ('N012',
  'UI#013',
  'QGroupBox',
  'grpPresetMenuContents',
  'Menu contents',
  'Preset path menu',
  'Menu contents',
  '',
  '',
  'Controls what appears in the menu'),
 ('N013',
  'UI#014',
  'QCheckBox',
  'chkMenuLastUsed',
  'Show Last used folder',
  'Preset path menu',
  'Menu contents',
  'preset_menu/show_last_used',
  'True',
  'Menu source toggle'),
 ('N014',
  'UI#015',
  'QCheckBox',
  'chkMenuCurrentFile',
  'Show Current file folder',
  'Preset path menu',
  'Menu contents',
  'preset_menu/show_current_file_folder',
  'True',
  'Menu source toggle'),
 ('N015',
  'UI#016',
  'QCheckBox',
  'chkMenuProjectHome',
  'Show Project home',
  'Preset path menu',
  'Menu contents',
  'preset_menu/show_project_home',
  'True',
  'Menu source toggle'),
 ('N016',
  'UI#017',
  'QCheckBox',
  'chkMenuQgzFolder',
  'Show QGZ folder',
  'Preset path menu',
  'Menu contents',
  'preset_menu/show_qgz_folder',
  'True',
  'Menu source toggle'),
 ('N017',
  'UI#018',
  'QCheckBox',
  'chkMenuPresets',
  'Show preset folders',
  'Preset path menu',
  'Menu contents',
  'preset_menu/show_preset_folders',
  'True',
  'Menu source toggle'),
 ('N018',
  'UI#019',
  'QCheckBox',
  'chkMenuDesktop',
  'Show Desktop',
  'Preset path menu',
  'Menu contents',
  'preset_menu/show_desktop',
  'False',
  'Menu source toggle'),
 ('N019',
  'UI#020',
  'QSpinBox',
  'spinHoldDelayMs',
  'Hold action delay',
  'General',
  'Timing',
  'holdDelayMs',
  '500',
  'Delay for hold actions in milliseconds; range 200-2000'),
 ('N020',
  'UI#021',
  'QSpinBox',
  'spinStartupDelayMs',
  'Startup delay before event filter starts',
  'General',
  'Timing',
  'startupDelayMs',
  '10000',
  'Delays event filter installation after QGIS startup; range 0-60000 ms'),
 ('N021',
  'UI#031',
  'QCheckBox',
  'chkMenuDocuments',
  'Show Documents',
  'Preset path menu',
  'Menu contents',
  'preset_menu/show_documents',
  'False',
  'Menu source toggle'),
 ('N022',
  'UI#032',
  'QCheckBox',
  'chkMenuDownloads',
  'Show Downloads',
  'Preset path menu',
  'Menu contents',
  'preset_menu/show_downloads',
  'False',
  'Menu source toggle'),
 ('N023',
  'UI#033',
  'QGroupBox',
  'grpPresetMenuOrder',
  'Menu item order',
  'Preset path menu',
  'Menu item order',
  '',
  '',
  'Move menu sections up/down'),
 ('N024',
  'UI#034',
  'QListWidget',
  'lstPresetMenuOrder',
  'Preset path menu order',
  'Preset path menu',
  'Menu item order',
  'preset_menu/order',
  'last_used,current_file_folder,project_home,qgz_folder,preset_folders',
  'Order of menu sources'),
 ('N025',
  'UI#035',
  'QPushButton',
  'btnPresetMenuMoveUp',
  'Move up',
  'Preset path menu',
  'Menu item order',
  '',
  '',
  'Moves selected menu source up'),
 ('N026',
  'UI#036',
  'QPushButton',
  'btnPresetMenuMoveDown',
  'Move down',
  'Preset path menu',
  'Menu item order',
  '',
  '',
  'Moves selected menu source down'),
 ('N027',
  'UI#037',
  'QCheckBox',
  'chkMenuCreateMissing',
  'Create missing folders when selected from menu',
  'Preset path menu',
  'Options',
  'preset_menu/create_missing_on_select',
  'True',
  'Creates selected menu folder if missing'),
 ('N028',
  'UI#038',
  'QCheckBox',
  'chkMenuRememberLast',
  'Remember selected menu folder as Last used folder',
  'Preset path menu',
  'Options',
  'preset_menu/remember_selected_as_last_used',
  'True',
  'Updates last-used from menu selection'),
 ('N029',
  'UI#039',
  'QComboBox',
  'cboMenuUnresolved',
  'Unresolved menu items',
  'Preset path menu',
  'Options',
  'preset_menu/unresolvedMode',
  'hide',
  'Hide or disable unresolved items'),
 ('N030',
  'UI#050',
  'QLabel',
  'lblSaveExportDescription',
  'Save / Export buttons description',
  'Save / Export buttons',
  'Description',
  '',
  '',
  'Description/examples for this type'),
 ('N031',
  'UI#051',
  'QGroupBox',
  'grpActions_save_export',
  'Save / Export buttons browse button actions',
  'Save / Export buttons',
  'Browse button actions',
  '',
  '',
  'Mouse-action mapping group'),
 ('N032',
  'UI#052',
  'QComboBox',
  'cbo_save_export_left_click',
  'Save / Export buttons - Left click',
  'Save / Export buttons',
  'Browse button actions',
  'save_export/action_left_click',
  'native',
  'Mouse-action mapping'),
 ('N033',
  'UI#053',
  'QComboBox',
  'cbo_save_export_left_double_click',
  'Save / Export buttons - Left double-click',
  'Save / Export buttons',
  'Browse button actions',
  'save_export/action_left_double_click',
  'do_nothing',
  'Mouse-action mapping'),
 ('N034',
  'UI#054',
  'QComboBox',
  'cbo_save_export_left_hold',
  'Save / Export buttons - Left click and hold',
  'Save / Export buttons',
  'Browse button actions',
  'save_export/action_left_hold',
  'do_nothing',
  'Mouse-action mapping'),
 ('N035',
  'UI#055',
  'QComboBox',
  'cbo_save_export_right_click',
  'Save / Export buttons - Right click',
  'Save / Export buttons',
  'Browse button actions',
  'save_export/action_right_click',
  'show_menu',
  'Mouse-action mapping'),
 ('N036',
  'UI#056',
  'QComboBox',
  'cbo_save_export_right_double_click',
  'Save / Export buttons - Right double-click',
  'Save / Export buttons',
  'Browse button actions',
  'save_export/action_right_double_click',
  'open_folder',
  'Mouse-action mapping'),
 ('N037',
  'UI#057',
  'QComboBox',
  'cbo_save_export_middle_click',
  'Save / Export buttons - Middle click',
  'Save / Export buttons',
  'Browse button actions',
  'save_export/action_middle_click',
  'do_nothing',
  'Mouse-action mapping'),
 ('N038',
  'UI#059',
  'QCheckBox',
  'chkSaveExportRasterNoExt',
  'Raster export paths',
  'Save / Export buttons',
  'Options',
  'save_export/rasterNoExt',
  'True',
  'No extension for raster autofill'),
 ('N039',
  'UI#060',
  'QComboBox',
  'cboSaveExportMissing',
  'If Save / Export folder is missing',
  'Save / Export buttons',
  'Options',
  'save_export/missingDir',
  'leave',
  ''),
 ('N040',
  'UI#070',
  'QLabel',
  'lblSaveFileDescription',
  'Save-file path boxes description',
  'Save-file path boxes',
  'Description',
  '',
  '',
  'Description/examples for this type'),
 ('N041',
  'UI#071',
  'QGroupBox',
  'grpActions_save_file',
  'Save-file path boxes browse button actions',
  'Save-file path boxes',
  'Browse button actions',
  '',
  '',
  'Mouse-action mapping group'),
 ('N042',
  'UI#072',
  'QComboBox',
  'cbo_save_file_left_click',
  'Save-file path boxes - Left click',
  'Save-file path boxes',
  'Browse button actions',
  'save_file/action_left_click',
  'native',
  'Mouse-action mapping'),
 ('N043',
  'UI#073',
  'QComboBox',
  'cbo_save_file_left_double_click',
  'Save-file path boxes - Left double-click',
  'Save-file path boxes',
  'Browse button actions',
  'save_file/action_left_double_click',
  'do_nothing',
  'Mouse-action mapping'),
 ('N044',
  'UI#074',
  'QComboBox',
  'cbo_save_file_left_hold',
  'Save-file path boxes - Left click and hold',
  'Save-file path boxes',
  'Browse button actions',
  'save_file/action_left_hold',
  'do_nothing',
  'Mouse-action mapping'),
 ('N045',
  'UI#075',
  'QComboBox',
  'cbo_save_file_right_click',
  'Save-file path boxes - Right click',
  'Save-file path boxes',
  'Browse button actions',
  'save_file/action_right_click',
  'show_menu',
  'Mouse-action mapping'),
 ('N046',
  'UI#076',
  'QComboBox',
  'cbo_save_file_right_double_click',
  'Save-file path boxes - Right double-click',
  'Save-file path boxes',
  'Browse button actions',
  'save_file/action_right_double_click',
  'open_folder',
  'Mouse-action mapping'),
 ('N047',
  'UI#077',
  'QComboBox',
  'cbo_save_file_middle_click',
  'Save-file path boxes - Middle click',
  'Save-file path boxes',
  'Browse button actions',
  'save_file/action_middle_click',
  'do_nothing',
  'Mouse-action mapping'),
 ('N048',
  'UI#078',
  'QCheckBox',
  'chkSaveFileAutofill',
  'Enable autofill for save-file path boxes',
  'Save-file path boxes',
  'Options',
  'save_file/autofillEnabled',
  'False',
  ''),
 ('N049',
  'UI#080',
  'QComboBox',
  'cboSaveFileMissing',
  'If save-file folder is missing',
  'Save-file path boxes',
  'Options',
  'save_file/missingDir',
  'leave',
  ''),
 ('N050',
  'UI#090',
  'QLabel',
  'lblFolderDescription',
  'Folder path boxes description',
  'Folder path boxes',
  'Description',
  '',
  '',
  'Description/examples for this type'),
 ('N051',
  'UI#091',
  'QGroupBox',
  'grpActions_folder',
  'Folder path boxes browse button actions',
  'Folder path boxes',
  'Browse button actions',
  '',
  '',
  'Mouse-action mapping group'),
 ('N052',
  'UI#092',
  'QComboBox',
  'cbo_folder_left_click',
  'Folder path boxes - Left click',
  'Folder path boxes',
  'Browse button actions',
  'folder/action_left_click',
  'native',
  'Mouse-action mapping'),
 ('N053',
  'UI#093',
  'QComboBox',
  'cbo_folder_left_double_click',
  'Folder path boxes - Left double-click',
  'Folder path boxes',
  'Browse button actions',
  'folder/action_left_double_click',
  'do_nothing',
  'Mouse-action mapping'),
 ('N054',
  'UI#094',
  'QComboBox',
  'cbo_folder_left_hold',
  'Folder path boxes - Left click and hold',
  'Folder path boxes',
  'Browse button actions',
  'folder/action_left_hold',
  'do_nothing',
  'Mouse-action mapping'),
 ('N055',
  'UI#095',
  'QComboBox',
  'cbo_folder_right_click',
  'Folder path boxes - Right click',
  'Folder path boxes',
  'Browse button actions',
  'folder/action_right_click',
  'show_menu',
  'Mouse-action mapping'),
 ('N056',
  'UI#096',
  'QComboBox',
  'cbo_folder_right_double_click',
  'Folder path boxes - Right double-click',
  'Folder path boxes',
  'Browse button actions',
  'folder/action_right_double_click',
  'open_folder',
  'Mouse-action mapping'),
 ('N057',
  'UI#097',
  'QComboBox',
  'cbo_folder_middle_click',
  'Folder path boxes - Middle click',
  'Folder path boxes',
  'Browse button actions',
  'folder/action_middle_click',
  'do_nothing',
  'Mouse-action mapping'),
 ('N058',
  'UI#098',
  'QCheckBox',
  'chkFolderAutofill',
  'Enable autofill for folder path boxes',
  'Folder path boxes',
  'Options',
  'folder/autofillEnabled',
  'False',
  ''),
 ('N059',
  'UI#099',
  'QComboBox',
  'cboFolderMissing',
  'If folder path is missing',
  'Folder path boxes',
  'Options',
  'folder/missingDir',
  'leave',
  ''),
 ('N060',
  'UI#110',
  'QLabel',
  'lblOpenFileDescription',
  'Open-file path boxes description',
  'Open-file path boxes',
  'Description',
  '',
  '',
  'Description/examples for this type'),
 ('N061',
  'UI#111',
  'QGroupBox',
  'grpActions_open_file',
  'Open-file path boxes browse button actions',
  'Open-file path boxes',
  'Browse button actions',
  '',
  '',
  'Mouse-action mapping group'),
 ('N062',
  'UI#112',
  'QComboBox',
  'cbo_open_file_left_click',
  'Open-file path boxes - Left click',
  'Open-file path boxes',
  'Browse button actions',
  'open_file/action_left_click',
  'native',
  'Mouse-action mapping'),
 ('N063',
  'UI#113',
  'QComboBox',
  'cbo_open_file_left_double_click',
  'Open-file path boxes - Left double-click',
  'Open-file path boxes',
  'Browse button actions',
  'open_file/action_left_double_click',
  'do_nothing',
  'Mouse-action mapping'),
 ('N064',
  'UI#114',
  'QComboBox',
  'cbo_open_file_left_hold',
  'Open-file path boxes - Left click and hold',
  'Open-file path boxes',
  'Browse button actions',
  'open_file/action_left_hold',
  'do_nothing',
  'Mouse-action mapping'),
 ('N065',
  'UI#115',
  'QComboBox',
  'cbo_open_file_right_click',
  'Open-file path boxes - Right click',
  'Open-file path boxes',
  'Browse button actions',
  'open_file/action_right_click',
  'show_menu',
  'Mouse-action mapping'),
 ('N066',
  'UI#116',
  'QComboBox',
  'cbo_open_file_right_double_click',
  'Open-file path boxes - Right double-click',
  'Open-file path boxes',
  'Browse button actions',
  'open_file/action_right_double_click',
  'open_folder',
  'Mouse-action mapping'),
 ('N067',
  'UI#117',
  'QComboBox',
  'cbo_open_file_middle_click',
  'Open-file path boxes - Middle click',
  'Open-file path boxes',
  'Browse button actions',
  'open_file/action_middle_click',
  'do_nothing',
  'Mouse-action mapping'),
 ('N068',
  'UI#118',
  'QCheckBox',
  'chkOpenFileAutofill',
  'Allow autofill for open-file path boxes',
  'Open-file path boxes',
  'Options',
  'open_file/autofillEnabled',
  'True',
  ''),
 ('N069',
  'UI#120',
  'QComboBox',
  'cboOpenFileMissing',
  'If open-file folder is missing',
  'Open-file path boxes',
  'Options',
  'open_file/missingDir',
  'leave',
  ''),
 ('N070',
  'UI#130',
  'QLabel',
  'lblLegacyWarning',
  'Custom / Advanced warning',
  'Custom / Advanced Buttons',
  'Warning / purpose',
  '',
  '',
  'Compact advanced-mode warning and usage note'),
 ('N071',
  'UI#131',
  'QCheckBox',
  'chkLegacyEnabled',
  'Enable custom / advanced button support',
  'Custom / Advanced Buttons',
  'Main controls',
  'legacy/enabled',
  'False',
  'Master enable for allowlisted ordinary/custom buttons'),
 ('N072',
  'UI#131A',
  'QGroupBox',
  'grpLegacyMainControls',
  'Main controls',
  'Custom / Advanced Buttons',
  'Main controls',
  '',
  '',
  'Combined enable, button types, and inspector controls'),
 ('N073',
  'UI#132',
  'QCheckBox',
  'chkLegacyMiddleInspector',
  'Enable middle-double-click widget inspector',
  'Custom / Advanced Buttons',
  'Main controls',
  'legacy/middleInspectEnabled',
  'False',
  'Middle double-click any UI item to capture dialog title, item type, item text, and item '
  'objectName'),
 ('N074',
  'UI#132A',
  'QLabel',
  'lblLegacyInspectorNote',
  'Inspector note',
  'Custom / Advanced Buttons',
  'Main controls',
  '',
  '',
  'Explains the middle-double-click inspector for any UI item'),
 ('N075',
  'UI#133',
  'QGroupBox',
  'grpActions_legacy',
  'Browse button actions',
  'Custom / Advanced Buttons',
  'Mouse actions',
  '',
  '',
  'Mouse actions for matched Custom / Advanced buttons'),
 ('N076',
  'UI#134',
  'QComboBox',
  'cbo_legacy_left_double',
  'Left double-click action',
  'Custom / Advanced Buttons',
  'Mouse actions',
  'legacy/action_left_double',
  'Do nothing',
  'Optional action on left double-click'),
 ('N077',
  'UI#135',
  'QComboBox',
  'cbo_legacy_left_hold',
  'Left click-and-hold action',
  'Custom / Advanced Buttons',
  'Mouse actions',
  'legacy/action_left_hold',
  'Do nothing',
  'Optional action on left click-and-hold'),
 ('N078',
  'UI#136',
  'QComboBox',
  'cbo_legacy_right_click',
  'Right-click action',
  'Custom / Advanced Buttons',
  'Mouse actions',
  'legacy/action_right_click',
  'Show preset path menu',
  'Optional action on right-click'),
 ('N079',
  'UI#137',
  'QComboBox',
  'cbo_legacy_middle_click',
  'Middle-click action',
  'Custom / Advanced Buttons',
  'Mouse actions',
  'legacy/action_middle_click',
  'Do nothing',
  'Optional action on middle-click'),
 ('N080',
  'UI#139B',
  'QCheckBox',
  'chkLegacyDebugBypass',
  'Bypass all allowlists',
  'Custom / Advanced Buttons',
  'Detection rules',
  'legacy/debugBypass',
  'False',
  'Advanced feature: ignores all allowlists while button type safeguards still apply'),
 ('N081',
  'UI#139C',
  'QCheckBox',
  'chkLegacyBypassDialogAllowlist',
  'Bypass dialog title allowlist',
  'Custom / Advanced Buttons',
  'Detection rules',
  'legacy/bypassDialogAllowlist',
  'False',
  'When enabled, dialog title keywords are ignored while other safeguards still apply'),
 ('N082',
  'UI#139D',
  'QCheckBox',
  'chkLegacyBypassButtonTextAllowlist',
  'Bypass button text allowlist',
  'Custom / Advanced Buttons',
  'Detection rules',
  'legacy/bypassButtonTextAllowlist',
  'False',
  'When enabled, button text allowlist is ignored while other safeguards still apply'),
 ('N083',
  'UI#139E',
  'QCheckBox',
  'chkLegacyBypassButtonObjectAllowlist',
  'Bypass button objectName allowlist',
  'Custom / Advanced Buttons',
  'Detection rules',
  'legacy/bypassButtonObjectAllowlist',
  'False',
  'When enabled, button objectName allowlist is ignored while other safeguards still apply'),
 ('N084',
  'UI#139F',
  'QCheckBox',
  'chkLegacyBypassTargetObjectAllowlist',
  'Bypass target textbox objectName allowlist',
  'Custom / Advanced Buttons',
  'Detection rules',
  'legacy/bypassTargetObjectAllowlist',
  'False',
  'When enabled, target objectName list is ignored and target search mode is used'),
 ('N085',
  'UI#140',
  'QCheckBox',
  'chkLegacyDetectQToolButton',
  'QToolButton',
  'Custom / Advanced Buttons',
  'Main controls',
  'legacy/detectQToolButton',
  'True',
  'Allow Custom / Advanced detection on QToolButton controls only for this tab'),
 ('N086',
  'UI#141',
  'QCheckBox',
  'chkLegacyDetectQPushButton',
  'QPushButton',
  'Custom / Advanced Buttons',
  'Main controls',
  'legacy/detectQPushButton',
  'True',
  'Allow Custom / Advanced detection on ordinary QPushButton controls only for this tab'),
 ('N087',
  'UI#142A',
  'QCheckBox',
  'chkLegacyDetectQCommandLinkButton',
  'QCommandLinkButton',
  'Custom / Advanced Buttons',
  'Main controls',
  'legacy/detectQCommandLinkButton',
  'False',
  'Advanced button type; uncommon in QGIS plugins'),
 ('N088',
  'UI#142B',
  'QCheckBox',
  'chkLegacyDetectQCheckBox',
  'QCheckBox',
  'Custom / Advanced Buttons',
  'Main controls',
  'legacy/detectQCheckBox',
  'False',
  'Advanced button type; can catch tick boxes, keep off unless needed'),
 ('N089',
  'UI#142C',
  'QCheckBox',
  'chkLegacyDetectQRadioButton',
  'QRadioButton',
  'Custom / Advanced Buttons',
  'Main controls',
  'legacy/detectQRadioButton',
  'False',
  'Advanced button type; usually option controls, keep off unless needed'),
 ('N090',
  'UI#142D',
  'QCheckBox',
  'chkLegacyDetectOtherAbstractButton',
  'Other QAbstractButton',
  'Custom / Advanced Buttons',
  'Main controls',
  'legacy/detectOtherAbstractButton',
  'False',
  'Broad fallback for custom/uncommon button subclasses'),
 ('N091',
  'UI#140A',
  'QLabel',
  'lblLegacyButtonTypes',
  'Button types',
  'Custom / Advanced Buttons',
  'Main controls',
  '',
  '',
  'Label for button type toggles'),
 ('N092',
  'UI#143',
  'QLabel',
  'lblLegacyAllowlistNote',
  'Allowlist note',
  'Custom / Advanced Buttons',
  'Detection rules',
  '',
  '',
  'Explains blank allowlist and bypass behaviour'),
 ('N093',
  'UI#143A',
  'QGroupBox',
  'grpLegacyAllowlist',
  'Detection rules',
  'Custom / Advanced Buttons',
  'Detection rules',
  '',
  '',
  'Compact tabbed allowlists and bypasses'),
 ('N094',
  'UI#143B',
  'QTabWidget',
  'tabLegacyDetectionRules',
  'Detection rule tabs',
  'Custom / Advanced Buttons',
  'Detection rules',
  '',
  '',
  'Tabbed editor for dialog, button text, button objectName, and target textbox allowlists'),
 ('N095',
  'UI#144',
  'QPlainTextEdit',
  'txtLegacyDialogAllowlist',
  'Dialog title keywords',
  'Custom / Advanced Buttons',
  'Detection rules',
  'legacy/dialogAllowlist',
  'Another DXF Import/Converter\\n',
  'One dialog title keyword per line'),
 ('N096',
  'UI#145',
  'QPlainTextEdit',
  'txtLegacyButtonAllowlist',
  'Button text allowlist',
  'Custom / Advanced Buttons',
  'Detection rules',
  'legacy/buttonTextAllowlist',
  'Browse\\n',
  'One button text keyword per line'),
 ('N097',
  'UI#146',
  'QPlainTextEdit',
  'txtLegacyButtonObjectAllowlist',
  'Button objectName allowlist',
  'Custom / Advanced Buttons',
  'Detection rules',
  'legacy/buttonObjectAllowlist',
  'browseZielPfadOrDatei',
  'One button objectName per line'),
 ('N098',
  'UI#147',
  'QPlainTextEdit',
  'txtLegacyTargetObjectAllowlist',
  'Target textbox objectName allowlist',
  'Custom / Advanced Buttons',
  'Detection rules',
  'legacy/targetObjectAllowlist',
  'txtZielPfad',
  'One target textbox objectName per line'),
 ('N099',
  'UI#148',
  'QComboBox',
  'cboLegacyPathSearchMode',
  'Find target path box',
  'Custom / Advanced Buttons',
  'Target search',
  'legacy/pathSearchMode',
  'nearby',
  'Strict nearby / parent container / whole dialog cautious'),
 ('N100',
  'UI#148B',
  'QGroupBox',
  'grpLegacyTargetSearch',
  'Target path box search',
  'Custom / Advanced Buttons',
  'Target search',
  '',
  '',
  'Search mode group for textbox actions'),
 ('N101',
  'UI#148A',
  'QLabel',
  'lblLegacyTargetSearchNote',
  'Target search note',
  'Custom / Advanced Buttons',
  'Target search',
  '',
  '',
  'Explains target detection only required for textbox actions'),
 ('N102',
  'UI#149',
  'QLabel',
  'lblLegacyDiagnosticsNote',
  'Diagnostics note',
  'Custom / Advanced Buttons',
  'Diagnostics',
  '',
  '',
  'Points to scan active dialog and middle-double-click UI item inspector'),
 ('N103',
  'UI#149A',
  'QGroupBox',
  'grpLegacyDiagnostics',
  'Diagnostics',
  'Custom / Advanced Buttons',
  'Diagnostics',
  '',
  '',
  'Compact diagnostics section'),
 ('N104',
  'UI#160',
  'QLabel',
  'lblPresetDescription',
  'Preset folders description',
  'Preset folders',
  'Description',
  '',
  '',
  'Explains presets'),
 ('N105',
  'UI#161',
  'QPlainTextEdit',
  'txtPresets',
  'Preset folders',
  'Preset folders',
  'Editor',
  'presets',
  'Current file folder / Project home / QGZ folder',
  'One preset per line as name=path'),
 ('N106',
  'UI#164',
  'QPushButton',
  'btnTestPresets',
  'Preview selected preset',
  'Preset folders',
  'Preview',
  '',
  '',
  'Refreshes resolved preset preview'),
 ('N107',
  'UI#165',
  'QPushButton',
  'btnPresetExamples',
  'Reset default presets',
  'Preset folders',
  'Defaults',
  '',
  '',
  'Restores default preset text'),
 ('N108',
  'UI#166',
  'QPlainTextEdit',
  'txtPresetPreview',
  'Resolved preset preview',
  'Preset folders',
  'Preview',
  '',
  '',
  'Shows resolved preset paths'),
 ('N109',
  'UI#180',
  'QLabel',
  'lblDebugDescription',
  'Debug / About description',
  'Debug / About',
  'Description',
  '',
  '',
  'Explains debug tab'),
 ('N110',
  'UI#182',
  'QPlainTextEdit',
  'txtDebugSummary',
  'Current debug summary',
  'Debug / About',
  'Debug',
  '',
  '',
  'Shows debug summary'),
 ('N111',
  'UI#183',
  'QPushButton',
  'btnAbout',
  'About',
  'Debug / About',
  'About',
  '',
  '',
  'Version/about dialog'),
 ('N112',
  'UI#184',
  'QGroupBox',
  'grpManualDebugTests',
  'Manual debug tests',
  'Debug / About',
  'Manual debug tests',
  '',
  '',
  'Manual buttons to confirm logging and trace display'),
 ('N113',
  'UI#185',
  'QPushButton',
  'btnTestDebugLog',
  'Test debug log',
  'Debug / About',
  'Manual debug tests',
  '',
  '',
  'Writes a simple FGQEP01 test message to QGIS log and message bar'),
 ('N114',
  'UI#186',
  'QPushButton',
  'btnTestLeftActionTrace',
  'Test left-action trace',
  'Debug / About',
  'Manual debug tests',
  '',
  '',
  'Adds a manual entry to Recent left-action trace'),
 ('N115',
  'UI#187',
  'QPushButton',
  'btnClearLeftActionTrace',
  'Clear trace',
  'Debug / About',
  'Manual debug tests',
  '',
  '',
  'Clears Recent left-action trace'),
 ('N116',
  'UI#188',
  'QLabel',
  'lblLastDebugTest',
  'Last debug test',
  'Debug / About',
  'Manual debug tests',
  '',
  '',
  'Shows the last manual debug test time'),
 ('N117',
  'UI#189',
  'QLabel',
  'lblTestBrowseButton',
  'Test browse button label',
  'Debug / About',
  'Manual debug tests',
  '',
  '',
  'Label for fake browse test button'),
 ('N118',
  'UI#190',
  'QPushButton',
  'btnSaveSettings',
  'Save settings',
  'Dialog buttons',
  'Dialog',
  '',
  '',
  'Saves and closes settings'),
 ('N119',
  'UI#190',
  'QToolButton',
  'btnTestBrowseButton',
  'Fake browse test button',
  'Debug / About',
  'Manual debug tests',
  '',
  '',
  'Fake [...] browse button for testing click/double-click/hold/right/middle events'),
 ('N120',
  'UI#191',
  'QPushButton',
  'btnClose',
  'Close',
  'Dialog buttons',
  'Dialog',
  '',
  '',
  'Closes settings without saving changes'),
 ('N121',
  'UI#191',
  'QLabel',
  'lblTestBrowseButtonHelp',
  'Fake browse test help',
  'Debug / About',
  'Manual debug tests',
  '',
  '',
  'Explains diagnostic fake browse button'),
 ('N122',
  'UI#192',
  'QPushButton',
  'btnScanActiveDialogButtons',
  'Scan active dialog buttons',
  'Debug / About',
  'Manual debug tests',
  '',
  '',
  'Lists buttons and path/text widgets in the currently active QDialog for Custom / Advanced '
  'Browse button diagnostics'),
 ('N123',
  'UI#193',
  'QPushButton',
  'btnApplySettings',
  'Apply',
  'Settings dialog',
  'Footer',
  '',
  '',
  'Save settings, reload cache, and keep window open'),
 ('N124',
  'UI#230',
  'QPushButton',
  'btnInsertVariablePopup',
  'Insert variable / path',
  'Preset folders',
  'Helper popup',
  '',
  '',
  'Opens insert-variable popup'),
 ('N125',
  'UI#231',
  'QLabel',
  'lblInsertVariablePopupDescription',
  'Insert variable popup description',
  'Insert variable / path popup',
  'Description',
  '',
  '',
  'Popup stays open for multiple inserts'),
 ('N126',
  'UI#232',
  'QGroupBox',
  'grpInsertCommonpaths',
  'Common paths',
  'Insert variable / path popup',
  'Common paths',
  '',
  '',
  'Common paths helper buttons'),
 ('N127',
  'UI#233',
  'QPushButton',
  'btnPopupInsertToken_current_file_folder',
  'Insert Current file folder',
  'Insert variable / path popup',
  'Common paths',
  '',
  '{current_file_folder}',
  'Inserts token into preset editor'),
 ('N128',
  'UI#234',
  'QPushButton',
  'btnPopupInsertToken_project_home',
  'Insert Project home',
  'Insert variable / path popup',
  'Common paths',
  '',
  '{project_home}',
  'Inserts token into preset editor'),
 ('N129',
  'UI#235',
  'QPushButton',
  'btnPopupInsertToken_qgz_folder',
  'Insert QGZ folder',
  'Insert variable / path popup',
  'Common paths',
  '',
  '{qgz_folder}',
  'Inserts token into preset editor'),
 ('N130',
  'UI#236',
  'QGroupBox',
  'grpInsertProject',
  'Project',
  'Insert variable / path popup',
  'Project',
  '',
  '',
  'Project helper buttons'),
 ('N131',
  'UI#237',
  'QPushButton',
  'btnPopupInsertToken_project_name',
  'Insert Project name',
  'Insert variable / path popup',
  'Project',
  '',
  '{project_name}',
  'Inserts token into preset editor'),
 ('N132',
  'UI#238',
  'QPushButton',
  'btnPopupInsertToken_project_dirname',
  'Insert Project folder name',
  'Insert variable / path popup',
  'Project',
  '',
  '{project_dirname}',
  'Inserts token into preset editor'),
 ('N133',
  'UI#239',
  'QPushButton',
  'btnPopupInsertToken_project_file',
  'Insert Project file',
  'Insert variable / path popup',
  'Project',
  '',
  '{project_file}',
  'Inserts token into preset editor'),
 ('N134',
  'UI#240',
  'QPushButton',
  'btnPopupInsertToken_project_file_name',
  'Insert Project file name',
  'Insert variable / path popup',
  'Project',
  '',
  '{project_file_name}',
  'Inserts token into preset editor'),
 ('N135',
  'UI#241',
  'QPushButton',
  'btnPopupInsertToken_project_file_base',
  'Insert Project file base',
  'Insert variable / path popup',
  'Project',
  '',
  '{project_file_base}',
  'Inserts token into preset editor'),
 ('N136',
  'UI#242',
  'QGroupBox',
  'grpInsertSystem',
  'System',
  'Insert variable / path popup',
  'System',
  '',
  '',
  'System helper buttons'),
 ('N137',
  'UI#243',
  'QPushButton',
  'btnPopupInsertToken_user',
  'Insert User name',
  'Insert variable / path popup',
  'System',
  '',
  '{user}',
  'Inserts token into preset editor'),
 ('N138',
  'UI#244',
  'QPushButton',
  'btnPopupInsertToken_home',
  'Insert User home',
  'Insert variable / path popup',
  'System',
  '',
  '{home}',
  'Inserts token into preset editor'),
 ('N139',
  'UI#245',
  'QPushButton',
  'btnPopupInsertToken_desktop',
  'Insert Desktop',
  'Insert variable / path popup',
  'System',
  '',
  '{desktop}',
  'Inserts token into preset editor'),
 ('N140',
  'UI#246',
  'QPushButton',
  'btnPopupInsertToken_documents',
  'Insert Documents',
  'Insert variable / path popup',
  'System',
  '',
  '{documents}',
  'Inserts token into preset editor'),
 ('N141',
  'UI#247',
  'QPushButton',
  'btnPopupInsertToken_downloads',
  'Insert Downloads',
  'Insert variable / path popup',
  'System',
  '',
  '{downloads}',
  'Inserts token into preset editor'),
 ('N142',
  'UI#248',
  'QPushButton',
  'btnPopupInsertToken_temp',
  'Insert Temp',
  'Insert variable / path popup',
  'System',
  '',
  '{temp}',
  'Inserts token into preset editor'),
 ('N143',
  'UI#249',
  'QGroupBox',
  'grpInsertQGIS',
  'QGIS',
  'Insert variable / path popup',
  'QGIS',
  '',
  '',
  'QGIS helper buttons'),
 ('N144',
  'UI#250',
  'QPushButton',
  'btnPopupInsertToken_qgis_profile',
  'Insert QGIS profile',
  'Insert variable / path popup',
  'QGIS',
  '',
  '{qgis_profile}',
  'Inserts token into preset editor'),
 ('N145',
  'UI#251',
  'QGroupBox',
  'grpInsertDatetime',
  'Date/time',
  'Insert variable / path popup',
  'Date/time',
  '',
  '',
  'Date/time helper buttons'),
 ('N146',
  'UI#252',
  'QPushButton',
  'btnPopupInsertToken_date_yyyyMMdd',
  'Insert Today yyyyMMdd',
  'Insert variable / path popup',
  'Date/time',
  '',
  '{date:yyyyMMdd}',
  'Inserts token into preset editor'),
 ('N147',
  'UI#253',
  'QPushButton',
  'btnPopupInsertToken_date_yyyy_MM',
  'Insert Month yyyy-MM',
  'Insert variable / path popup',
  'Date/time',
  '',
  '{date:yyyy-MM}',
  'Inserts token into preset editor'),
 ('N148',
  'UI#254',
  'QPushButton',
  'btnPopupInsertToken_date_yyyy',
  'Insert Year yyyy',
  'Insert variable / path popup',
  'Date/time',
  '',
  '{date:yyyy}',
  'Inserts token into preset editor'),
 ('N149',
  'UI#255',
  'QPushButton',
  'btnPopupInsertToken_date_yyyyMMdd_HHmmss',
  'Insert Now yyyyMMdd_HHmmss',
  'Insert variable / path popup',
  'Date/time',
  '',
  '{date:yyyyMMdd_HHmmss}',
  'Inserts token into preset editor'),
 ('N150',
  'UI#260',
  'QGroupBox',
  'grpInsertCustomVariables',
  'Custom variables',
  'Insert variable / path popup',
  'Custom variables',
  '',
  '',
  'Custom token helpers'),
 ('N151',
  'UI#261',
  'QLineEdit',
  'txtProjectVarName',
  'Project variable name',
  'Insert variable / path popup',
  'Custom variables',
  '',
  'project_code',
  'Custom project variable helper'),
 ('N152',
  'UI#262',
  'QPushButton',
  'btnInsertProjectVar',
  'Insert project variable',
  'Insert variable / path popup',
  'Custom variables',
  '',
  '{var:name}',
  'Inserts custom project variable token'),
 ('N153',
  'UI#263',
  'QLineEdit',
  'txtEnvVarName',
  'Environment variable name',
  'Insert variable / path popup',
  'Custom variables',
  '',
  'USERPROFILE',
  'Custom environment variable helper'),
 ('N154',
  'UI#264',
  'QPushButton',
  'btnInsertEnvVar',
  'Insert environment variable',
  'Insert variable / path popup',
  'Custom variables',
  '',
  '{env:NAME}',
  'Inserts custom environment variable token'),
 ('N155',
  'UI#265',
  'QLineEdit',
  'txtDateFormat',
  'Custom date format',
  'Insert variable / path popup',
  'Custom variables',
  '',
  'yyyyMMdd_HHmm',
  'Custom date/time format helper'),
 ('N156',
  'UI#266',
  'QPushButton',
  'btnInsertDateFormat',
  'Insert custom date',
  'Insert variable / path popup',
  'Custom variables',
  '',
  '{date:fmt}',
  'Inserts custom date token'),
 ('N157',
  'UI#267',
  'QLabel',
  'lblInsertPopupStatus',
  'Insert status',
  'Insert variable / path popup',
  'Status',
  '',
  '',
  'Shows most recently inserted token'),
 ('N158',
  'UI#268',
  'QPushButton',
  'btnCloseInsertVariablePopup',
  'Close',
  'Insert variable / path popup',
  'Dialog',
  '',
  '',
  'Closes popup'),
 ('N159',
  'UI#300',
  'QGroupBox',
  'grpCopy_save_export',
  'Save / Export buttons copy settings',
  'Save / Export buttons',
  'Copy settings',
  '',
  '',
  'Compact copy settings group'),
 ('N160',
  'UI#301',
  'QLabel',
  'lblCopyDesc_save_export',
  'Save / Export buttons copy settings label',
  'Save / Export buttons',
  'Copy settings',
  '',
  '',
  'Compact label for copy settings'),
 ('N161',
  'UI#302',
  'QToolButton',
  'btnCopySettingsTo_save_export',
  'Save / Export buttons copy settings to',
  'Save / Export buttons',
  'Copy settings',
  '',
  '',
  'Opens compact target-selection popup'),
 ('N162',
  'UI#303',
  'QLabel',
  'lblCopyStatus_save_export',
  'Save / Export buttons copy status',
  'Save / Export buttons',
  'Copy settings',
  '',
  '',
  'Shows copy operation result'),
 ('N163',
  'UI#310',
  'QGroupBox',
  'grpCopy_save_file',
  'Save-file path boxes copy settings',
  'Save-file path boxes',
  'Copy settings',
  '',
  '',
  'Compact copy settings group'),
 ('N164',
  'UI#311',
  'QLabel',
  'lblCopyDesc_save_file',
  'Save-file path boxes copy settings label',
  'Save-file path boxes',
  'Copy settings',
  '',
  '',
  'Compact label for copy settings'),
 ('N165',
  'UI#312',
  'QToolButton',
  'btnCopySettingsTo_save_file',
  'Save-file path boxes copy settings to',
  'Save-file path boxes',
  'Copy settings',
  '',
  '',
  'Opens compact target-selection popup'),
 ('N166',
  'UI#313',
  'QLabel',
  'lblCopyStatus_save_file',
  'Save-file path boxes copy status',
  'Save-file path boxes',
  'Copy settings',
  '',
  '',
  'Shows copy operation result'),
 ('N167',
  'UI#320',
  'QGroupBox',
  'grpCopy_folder',
  'Folder path boxes copy settings',
  'Folder path boxes',
  'Copy settings',
  '',
  '',
  'Compact copy settings group'),
 ('N168',
  'UI#321',
  'QLabel',
  'lblCopyDesc_folder',
  'Folder path boxes copy settings label',
  'Folder path boxes',
  'Copy settings',
  '',
  '',
  'Compact label for copy settings'),
 ('N169',
  'UI#322',
  'QToolButton',
  'btnCopySettingsTo_folder',
  'Folder path boxes copy settings to',
  'Folder path boxes',
  'Copy settings',
  '',
  '',
  'Opens compact target-selection popup'),
 ('N170',
  'UI#323',
  'QLabel',
  'lblCopyStatus_folder',
  'Folder path boxes copy status',
  'Folder path boxes',
  'Copy settings',
  '',
  '',
  'Shows copy operation result'),
 ('N171',
  'UI#330',
  'QGroupBox',
  'grpCopy_open_file',
  'Open-file path boxes copy settings',
  'Open-file path boxes',
  'Copy settings',
  '',
  '',
  'Compact copy settings group'),
 ('N172',
  'UI#331',
  'QLabel',
  'lblCopyDesc_open_file',
  'Open-file path boxes copy settings label',
  'Open-file path boxes',
  'Copy settings',
  '',
  '',
  'Compact label for copy settings'),
 ('N173',
  'UI#332',
  'QToolButton',
  'btnCopySettingsTo_open_file',
  'Open-file path boxes copy settings to',
  'Open-file path boxes',
  'Copy settings',
  '',
  '',
  'Opens compact target-selection popup'),
 ('N174',
  'UI#333',
  'QLabel',
  'lblCopyStatus_open_file',
  'Open-file path boxes copy status',
  'Open-file path boxes',
  'Copy settings',
  '',
  '',
  'Shows copy operation result'),
 ('N175',
  'UI#340',
  'QGroupBox',
  'grpCopy_legacy',
  'Custom / Advanced Buttons copy settings',
  'Custom / Advanced Buttons',
  'Copy settings',
  '',
  '',
  'Compact copy settings group'),
 ('N176',
  'UI#341',
  'QLabel',
  'lblCopyDesc_legacy',
  'Custom / Advanced Buttons copy settings label',
  'Custom / Advanced Buttons',
  'Copy settings',
  '',
  '',
  'Compact label for copy settings'),
 ('N177',
  'UI#342',
  'QToolButton',
  'btnCopySettingsTo_legacy',
  'Custom / Advanced Buttons copy settings to',
  'Custom / Advanced Buttons',
  'Copy settings',
  '',
  '',
  'Opens compact target-selection popup'),
 ('N178',
  'UI#343',
  'QLabel',
  'lblCopyStatus_legacy',
  'Custom / Advanced Buttons copy status',
  'Custom / Advanced Buttons',
  'Copy settings',
  '',
  '',
  'Shows copy operation result'),
 ('N179',
  'UI#057A',
  'QComboBox',
  'cboSaveExportAutofillContent',
  'Save / Export autofill content',
  'Save / Export buttons',
  'Options',
  'save_export/autofillContent',
  'layer_file_path',
  'Per-tab autofill source content'),
 ('N180',
  'UI#078A',
  'QComboBox',
  'cboSaveFileAutofillContent',
  'Save-file autofill content',
  'Save-file path boxes',
  'Options',
  'save_file/autofillContent',
  'preset_folder',
  'Per-tab autofill source content'),
 ('N181',
  'UI#098A',
  'QComboBox',
  'cboFolderAutofillContent',
  'Folder path-box autofill content',
  'Folder path boxes',
  'Options',
  'folder/autofillContent',
  'layer_file_folder',
  'Per-tab autofill source content'),
 ('N182',
  'UI#118A',
  'QComboBox',
  'cboOpenFileAutofillContent',
  'Open-file autofill content',
  'Open-file path boxes',
  'Options',
  'open_file/autofillContent',
  'layer_file_path',
  'Per-tab autofill source content'),
 ('N183',
  'UI#139A',
  'QComboBox',
  'cboLegacyAutofillContent',
  'Custom / Advanced autofill content',
  'Custom / Advanced Buttons',
  'Options',
  'legacy/autofillContent',
  'layer_file_path',
  'Per-tab autofill source content')]

def tooltip(ui_number, widget_class, object_name, caption, description):
    base = '{0} | {1} | {2} | "{3}"'.format(ui_number, widget_class, object_name, caption)
    if description:
        return base + "\n\n" + description
    return base
